- name: Gather and print local facts
  # quay.io/rhn_support_nreilly/terraform-ee
  hosts: localhost
  # become: true
  gather_facts: true
  tasks:
    - name: Print facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Ensure director exists
      ansible.builtin.file:
        path: /tmp/terraform/
        state: directory
        mode: 0755

    - name: Copy terraform module to work_dir
      ansible.builtin.copy:
        src: install.tf
        dest: /tmp/terraform/
        mode: "0664"

    - name: Copy terraform files to work_dir
      ansible.builtin.template:
        src: provider.tf
        dest: /tmp/terraform/
        mode: "0664"

    - name: Dump the terraform files
      ansible.builtin.shell:
        cmd: |
          cat /tmp/terraform/provider.tf
#    - name: Run terraform
#      cloud.terraform.terraform:
#        project_path: "/tmp/terraform/"
#        force_init: true
#        provider_upgrade: true
#        state: present
#      register: network_output
