- name: Gather and print local facts
  # quay.io/rhn_support_nreilly/terraform-ee
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Print facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Ensure director exists
      ansible.builtin.file:
        path: /tmp/terraform/
        state: directory
        mode: "0755"

    - name: Get list of files to copy
      ansible.builtin.find:
        path: terraform/files/
        file_type: file
        recurse: no
      register: terraform_files
        
    - name: Copy terraform module to work_dir
      ansible.builtin.copy:
        src: terraform/files/{{item}}
        dest: /tmp/terraform/
        mode: "0664"
      with_items:
      - "{{ terraform_files.files }}"

    - name: Copy terraform files to work_dir
      ansible.builtin.template:
        src: terraform/templates/terraform.tfvars.json.j2
        dest: /tmp/terraform/terraform.tfvars.json
        mode: "0664"

    - name: Dump the terraform files
      ansible.builtin.shell:
        cmd: |
          ls -lasR /tmp/terraform/

    - name: Run terraform
      cloud.terraform.terraform:
        project_path: "/tmp/terraform/"
        force_init: true
        provider_upgrade: true
        state: present
      register: network_output
